changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - "breaking-change"
    - title: Bug Fixes
      labels:
        - "bug"
    - title: New Features
      labels:
        - "enhancement"
    - title: Configuration
      labels:
        - "configuration"
    - title: Documentation
      labels:
        - "documentation"
    - title: Dependency Updates
      labels:
        - "dependencies"
    - title: Other Changes
      labels:
        - "*"
