"""Create table for held records, that are meant to be distributed to acoustic in time

Revision ID: b158cb1c877c
Revises: 8019ffa1614e
Create Date: 2021-04-22 01:50:49.197268

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSequence, Sequence

# revision identifiers, used by Alembic.
revision = "b158cb1c877c"  # pragma: allowlist secret
down_revision = "8019ffa1614e"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # Following command to create sequence added manually.
    op.execute(CreateSequence(Sequence("pending_id_sequence")))
    # End manually added commands

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_acoustic",
        sa.Column(
            "id",
            sa.Integer(),
            server_default=sa.text("nextval('pending_id_sequence')"),
            nullable=False,
        ),
        sa.Column("email_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("retry", sa.Integer(), nullable=False),
        sa.Column(
            "create_timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.email_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pending_acoustic")
    # ### end Alembic commands ###
