"""Updating relationship between pending records and emails

Revision ID: 5bd2b2155c71
Revises: 8019ffa1614e
Create Date: 2021-04-26 18:15:59.400264

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSequence, Sequence

# revision identifiers, used by Alembic.
revision = "5bd2b2155c71"  # pragma: allowlist secret
down_revision = "8019ffa1614e"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # Begin manually added commands
    op.execute(CreateSequence(Sequence("pending_id_sequence")))
    # End manually added commands

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_acoustic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("retry", sa.Integer(), nullable=False),
        sa.Column(
            "create_timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.email_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pending_acoustic")
    # ### end Alembic commands ###
