"""Creating table for pending acoustic records

Revision ID: cad3c933830b
Revises: bd7adf1a3801
Create Date: 2021-05-05 06:53:21.736467

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSequence, Sequence

# revision identifiers, used by Alembic.
revision = "cad3c933830b"  # pragma: allowlist secret
down_revision = "bd7adf1a3801"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # Following command to create sequence added manually.
    op.execute(CreateSequence(Sequence("pending_id_sequence")))
    # End manually added commands

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_acoustic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("retry", sa.Integer(), nullable=False),
        sa.Column(
            "create_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.email_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pending_acoustic")
    # ### end Alembic commands ###
