"""Adding indexes for main ids

Revision ID: bd7adf1a3801
Revises: 6367a2394c6c
Create Date: 2021-04-29 19:55:44.967467

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bd7adf1a3801"  # pragma: allowlist secret
down_revision = "6367a2394c6c"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_amo_user_id"), "amo", ["user_id"], unique=False)
    op.create_index(op.f("ix_emails_sfdc_id"), "emails", ["sfdc_id"], unique=False)
    op.create_index(
        op.f("ix_fxa_primary_email"), "fxa", ["primary_email"], unique=False
    )
    op.create_index(
        op.f("ix_mofo_mofo_contact_id"), "mofo", ["mofo_contact_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mofo_mofo_contact_id"), table_name="mofo")
    op.drop_index(op.f("ix_fxa_primary_email"), table_name="fxa")
    op.drop_index(op.f("ix_emails_sfdc_id"), table_name="emails")
    op.drop_index(op.f("ix_amo_user_id"), table_name="amo")
    # ### end Alembic commands ###
