"""Add Acoustic Newsletter Mapping

Revision ID: f8b8f6aa0e96
Revises: 06f24cc01c09
Create Date: 2022-11-15 12:20:10.096170

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f8b8f6aa0e96"  # pragma: allowlist secret
down_revision = "06f24cc01c09"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    acoustic_mapping_table = op.create_table(
        "acoustic_newsletter_mapping",
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("destination", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("source"),
    )
    # ### end Alembic commands ###

    # This mapping used to be hard-coded. We now initialize the freshly created
    # table with it, but the records of this table will likely be modified
    # eventually.
    MAIN_TABLE_SUBSCR_FLAGS = {
        # maps the Basket/CTMS newsletter name to the Acoustic name
        "about-mozilla": "sub_about_mozilla",
        "app-dev": "sub_apps_and_hacks",
        "common-voice": "sub_common_voice",
        "firefox-accounts-journey": "sub_firefox_accounts_journey",
        "firefox-news": "sub_firefox_news",
        "firefox-sweepstakes": "sub_firefox_sweepstakes",
        "hubs": "sub_hubs",
        "internet-health-report": "sub_internet_health_report",
        "knowledge-is-power": "sub_knowledge_is_power",
        "miti": "sub_miti",
        "mixed-reality": "sub_mixed_reality",
        "mozilla-and-you": "sub_firefox_news",
        "mozilla-fellowship-awardee-alumni": "sub_mozilla_fellowship_awardee_alumni",
        "mozilla-festival": "sub_mozilla_festival",
        "mozilla-foundation": "sub_mozilla_foundation",
        "mozilla-rally": "sub_rally",
        "mozilla-technology": "sub_mozilla_technology",
        "mozillians-nda": "sub_mozillians_nda",
        "security-privacy-news": "sub_security_privacy_news",
        "take-action-for-the-internet": "sub_take_action_for_the_internet",
        "test-pilot": "sub_test_pilot",
    }
    op.bulk_insert(
        acoustic_mapping_table,
        [{"source": k, "destination": v} for k, v in MAIN_TABLE_SUBSCR_FLAGS.items()],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("acoustic_newsletter_mapping")
    # ### end Alembic commands ###
