"""Add Acoustic field

Revision ID: 06f24cc01c09
Revises: 6c7724982996
Create Date: 2022-11-11 17:32:04.411812

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '06f24cc01c09'  # pragma: allowlist secret
down_revision = '6c7724982996'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    acoustic_field_table = op.create_table('acoustic_field',
    sa.Column('tablename', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tablename', 'field', name='pk_tablename_field')
    )
    # ### end Alembic commands ###

    # This list used to be hard-coded. We now initialize the freshly created
    # table with it, but the records of this table will likely be modified
    # eventually.
    VALID_ACOUSTIC_MAIN_TABLE_FIELDS = {
        "sfdc_id",
        "email",
        "amo_add_on_ids",
        "amo_display_name",
        "amo_email_opt_in",
        "amo_language",
        "amo_last_login",
        "amo_location",
        "amo_profile_url",
        "amo_user",
        "amo_user_id",
        "amo_username",
        "create_timestamp",
        "email_format",
        "email_id",
        "email_lang",
        "vpn_waitlist_geo",
        "vpn_waitlist_platform",
        "relay_waitlist_geo",
        "fxa_id",
        "fxa_account_deleted",
        "fxa_lang",
        "fxa_login_date",
        "fxa_first_service",
        "fxa_created_date",
        "fxa_primary_email",
        "double_opt_in",
        "has_opted_out_of_email",
        "mailing_country",
        "first_name",
        "last_name",
        "sumo_contributor",
        "sumo_user",
        "sumo_username",
        "basket_token",
        "unsubscribe_reason",
    }
    op.bulk_insert(acoustic_field_table, [
        {"tablename": "main", "field": f}
        for f in VALID_ACOUSTIC_MAIN_TABLE_FIELDS
    ]
)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acoustic_field')
    # ### end Alembic commands ###
