"""Add Waitlist table

Revision ID: 9c37ea9b5bba
Revises: f8b8f6aa0e96
Create Date: 2022-12-13 13:49:27.597613

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9c37ea9b5bba"  # pragma: allowlist secret
down_revision = "f8b8f6aa0e96"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "waitlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("geo", sa.String(length=100), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("fields", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "create_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.email_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_id", "name", name="uix_wl_email_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("waitlists")
    # ### end Alembic commands ###
