"""Add last error message to PendingAcousticRecord

Revision ID: a016433d3e8b
Revises: 4f6c48142631
Create Date: 2023-03-14 13:23:04.856490

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a016433d3e8b"  # pragma: allowlist secret
down_revision = "4f6c48142631"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pending_acoustic", sa.Column("last_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pending_acoustic", "last_error")
    # ### end Alembic commands ###
