"""Add unicity constraint in pending records

Revision ID: 375dd57cfed1
Revises: 8f93a0e590f0
Create Date: 2023-09-15 10:11:28.618091

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "375dd57cfed1"  # pragma: allowlist secret
down_revision = "8f93a0e590f0"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # Delete duplicate `pending_record` entries, keeping the latest one (highest `id`)
    op.execute(
        """
    DELETE FROM pending_acoustic
    WHERE id NOT IN
        (SELECT MAX(id)
         FROM pending_acoustic
         GROUP BY email_id)
    """
    )
    op.create_unique_constraint("uix_pr_email_id", "pending_acoustic", ["email_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_pr_email_id", "pending_acoustic", type_="unique")
    # ### end Alembic commands ###
