"""Add subscribed/unsub_reason to Waitlist

Revision ID: 2a0489304e03
Revises: a016433d3e8b
Create Date: 2023-06-19 13:40:43.345044

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a0489304e03"  # pragma: allowlist secret
down_revision = "a016433d3e8b"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("waitlists", sa.Column("subscribed", sa.Boolean(), nullable=True))
    op.add_column("waitlists", sa.Column("unsub_reason", sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Existing recoards are all subscriptions
    op.execute("UPDATE waitlists SET subscribed = true")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("waitlists", "unsub_reason")
    op.drop_column("waitlists", "subscribed")
    # ### end Alembic commands ###
