"""Add delete cascade to Email model

Revision ID: c8ede88755f3
Revises: a016433d3e8b
Create Date: 2023-03-15 22:32:16.992629

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8ede88755f3"  # pragma: allowlist secret
down_revision = "a016433d3e8b"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("amo_email_id_fkey", "amo", type_="foreignkey")
    op.create_foreign_key(
        "amo_email_id_fkey",
        "amo",
        "emails",
        ["email_id"],
        ["email_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fxa_email_id_fkey", "fxa", type_="foreignkey")
    op.create_foreign_key(
        "fxa_email_id_fkey",
        "fxa",
        "emails",
        ["email_id"],
        ["email_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("mofo_email_id_fkey", "mofo", type_="foreignkey")
    op.create_foreign_key(
        "mofo_email_id_fkey",
        "mofo",
        "emails",
        ["email_id"],
        ["email_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("newsletters_email_id_fkey", "newsletters", type_="foreignkey")
    op.create_foreign_key(
        "newsletters_email_id_fkey",
        "newsletters",
        "emails",
        ["email_id"],
        ["email_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "pending_acoustic_email_id_fkey", "pending_acoustic", type_="foreignkey"
    )
    op.create_foreign_key(
        "pending_acoustic_email_id_fkey",
        "pending_acoustic",
        "emails",
        ["email_id"],
        ["email_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("waitlists_email_id_fkey", "waitlists", type_="foreignkey")
    op.create_foreign_key(
        "waitlists_email_id_fkey",
        "waitlists",
        "emails",
        ["email_id"],
        ["email_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("waitlists_email_id_fkey", "waitlists", type_="foreignkey")
    op.create_foreign_key(
        "waitlists_email_id_fkey", "waitlists", "emails", ["email_id"], ["email_id"]
    )
    op.drop_constraint(
        "pending_acoustic_email_id_fkey", "pending_acoustic", type_="foreignkey"
    )
    op.create_foreign_key(
        "pending_acoustic_email_id_fkey",
        "pending_acoustic",
        "emails",
        ["email_id"],
        ["email_id"],
    )
    op.drop_constraint("newsletters_email_id_fkey", "newsletters", type_="foreignkey")
    op.create_foreign_key(
        "newsletters_email_id_fkey", "newsletters", "emails", ["email_id"], ["email_id"]
    )
    op.drop_constraint("mofo_email_id_fkey", "mofo", type_="foreignkey")
    op.create_foreign_key(
        "mofo_email_id_fkey", "mofo", "emails", ["email_id"], ["email_id"]
    )
    op.drop_constraint("fxa_email_id_fkey", "fxa", type_="foreignkey")
    op.create_foreign_key(
        "fxa_email_id_fkey", "fxa", "emails", ["email_id"], ["email_id"]
    )
    op.drop_constraint("amo_email_id_fkey", "amo", type_="foreignkey")
    op.create_foreign_key(
        "amo_email_id_fkey", "amo", "emails", ["email_id"], ["email_id"]
    )
    # ### end Alembic commands ###
