"""Remove background Acoustic sync

Revision ID: 432e8585fe17
Revises: 375dd57cfed1
Create Date: 2024-04-02 16:50:15.360114

In April 2024, we migrated from Acoustic to a new Email Service Provider (ESP).

Because of this, and because we're not directly integrating with the new ESP,
we're removing the background job to sync contact data with Acoustic.

"""

# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "432e8585fe17"  # pragma: allowlist secret
down_revision = "375dd57cfed1"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("acoustic_field")
    op.drop_table("pending_acoustic")
    op.drop_table("acoustic_newsletter_mapping")
    op.alter_column(
        "waitlists", "subscribed", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "waitlists", "subscribed", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.create_table(
        "acoustic_newsletter_mapping",
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("destination", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("source", name="acoustic_newsletter_mapping_pkey"),
    )
    op.create_table(
        "pending_acoustic",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("retry", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "create_timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "update_timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("last_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["email_id"], ["emails.email_id"], name="pending_acoustic_email_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="pending_acoustic_pkey"),
        sa.UniqueConstraint("email_id", name="uix_pr_email_id"),
    )
    op.create_table(
        "acoustic_field",
        sa.Column("tablename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("field", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("tablename", "field", name="pk_tablename_field"),
    )
    # ### end Alembic commands ###
