"""Add column to track API use

Revision ID: f2041a868dca
Revises: cea70cf9d626
Create Date: 2024-05-27 18:11:06.463499

"""
# pylint: disable=no-member invalid-name
# no-member is triggered by alembic.op, which has dynamically added functions
# invalid-name is triggered by migration file names with a date prefix
# invalid-name is triggered by top-level alembic constants like revision instead of REVISION

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f2041a868dca"  # pragma: allowlist secret
down_revision = "cea70cf9d626"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_client",
        sa.Column("last_access", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_client", "last_access")
    # ### end Alembic commands ###
